
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'APPEND CLASS COMMENT EXTENDS IDENTIFIER LCURLY PACKAGE RCURLY SEMICOLON STRINGBUILDERprogram : PACKAGE IDENTIFIER SEMICOLON classesclasses : classes classdefclasses :classdef : CLASS IDENTIFIER extends LCURLY methods RCURLYextends : EXTENDS IDENTIFIERextends :methods : methods methodmethods :method : IDENTIFIER LCURLY statements RCURLYstatements : statements statementstatements :statement : STRINGBUILDER IDENTIFIER SEMICOLONstatement : IDENTIFIER APPEND IDENTIFIER SEMICOLON'
    
_lr_action_items = {'PACKAGE':([0,],[2,]),'$end':([1,4,5,6,15,],[0,-3,-1,-2,-4,]),'IDENTIFIER':([2,7,10,11,13,16,17,18,20,21,22,23,26,27,],[3,8,12,-8,14,-7,-11,19,-9,-10,24,25,-12,-13,]),'SEMICOLON':([3,24,25,],[4,26,27,]),'CLASS':([4,5,6,15,],[-3,7,-2,-4,]),'EXTENDS':([8,],[10,]),'LCURLY':([8,9,12,14,],[-6,11,-5,17,]),'RCURLY':([11,13,16,17,18,20,21,26,27,],[-8,15,-7,-11,20,-9,-10,-12,-13,]),'STRINGBUILDER':([17,18,21,26,27,],[-11,22,-10,-12,-13,]),'APPEND':([19,],[23,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'classes':([4,],[5,]),'classdef':([5,],[6,]),'extends':([8,],[9,]),'methods':([11,],[13,]),'method':([13,],[16,]),'statements':([17,],[18,]),'statement':([18,],[21,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> PACKAGE IDENTIFIER SEMICOLON classes','program',4,'p_program','string_builder_ext.py',48),
  ('classes -> classes classdef','classes',2,'p_classes','string_builder_ext.py',53),
  ('classes -> <empty>','classes',0,'p_classes_empty','string_builder_ext.py',58),
  ('classdef -> CLASS IDENTIFIER extends LCURLY methods RCURLY','classdef',6,'p_classdef','string_builder_ext.py',63),
  ('extends -> EXTENDS IDENTIFIER','extends',2,'p_extends','string_builder_ext.py',68),
  ('extends -> <empty>','extends',0,'p_extends_empty','string_builder_ext.py',73),
  ('methods -> methods method','methods',2,'p_methods','string_builder_ext.py',78),
  ('methods -> <empty>','methods',0,'p_methods_empty','string_builder_ext.py',83),
  ('method -> IDENTIFIER LCURLY statements RCURLY','method',4,'p_method','string_builder_ext.py',88),
  ('statements -> statements statement','statements',2,'p_statements','string_builder_ext.py',100),
  ('statements -> <empty>','statements',0,'p_statements_empty','string_builder_ext.py',105),
  ('statement -> STRINGBUILDER IDENTIFIER SEMICOLON','statement',3,'p_statement','string_builder_ext.py',110),
  ('statement -> IDENTIFIER APPEND IDENTIFIER SEMICOLON','statement',4,'p_statement_append','string_builder_ext.py',115),
]
